
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 16 12:18:58 CST 2018
//----------------------------------------------------

package Source.CHTML;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int menorQue = 2;
  public static final int mayorQue = 3;
  public static final int idVariable = 9;
  public static final int decimal = 8;
  public static final int EOF = 0;
  public static final int numero = 7;
  public static final int inicioEncabezado = 6;
  public static final int error = 1;
  public static final int inicioChtml = 4;
  public static final int finChtml = 5;
}

