
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 20 16:33:25 CST 2018
//----------------------------------------------------

package Source.CHTML;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int mayorQue = 3;
  public static final int finCuerpo = 17;
  public static final int ancho = 28;
  public static final int finPanel = 31;
  public static final int fondo = 18;
  public static final int pathComillas = 10;
  public static final int idCcss = 25;
  public static final int rgb = 19;
  public static final int finEnlace = 42;
  public static final int inicioCuerpo = 16;
  public static final int finTitulo = 22;
  public static final int finChtml = 5;
  public static final int inicioCcss = 13;
  public static final int inicioTexto = 32;
  public static final int finEncabezado = 15;
  public static final int alto = 27;
  public static final int inicioEnlace = 41;
  public static final int menorQue = 2;
  public static final int grupo = 26;
  public static final int inicioTitulo = 21;
  public static final int alineado = 29;
  public static final int inicioEncabezado = 6;
  public static final int ruta = 8;
  public static final int inicioBoton = 39;
  public static final int EOF = 0;
  public static final int finCjs = 12;
  public static final int error = 1;
  public static final int finImagen = 34;
  public static final int finTexto = 33;
  public static final int metodo = 36;
  public static final int valorAlineado = 30;
  public static final int finCcss = 14;
  public static final int click = 37;
  public static final int id = 20;
  public static final int puntoComa = 11;
  public static final int finBoton = 40;
  public static final int inicioImagen = 35;
  public static final int path = 38;
  public static final int inicioPanel = 24;
  public static final int inicioChtml = 4;
  public static final int asignacion = 9;
  public static final int inicioCjs = 7;
  public static final int cadena = 23;
}

