
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Source.CCSS.Analizadores;

/** CUP generated class containing symbol constants. */
public class symCCSS {
  /* terminals */
  public static final int NUMERO = 40;
  public static final int PAR_DER = 10;
  public static final int fondoElemento = 32;
  public static final int mayuscula = 15;
  public static final int POR = 9;
  public static final int tamTex = 31;
  public static final int opaque = 23;
  public static final int negrilla = 13;
  public static final int derecha = 36;
  public static final int COR_DER = 3;
  public static final int letra = 30;
  public static final int IGUAL = 5;
  public static final int autoredimension = 20;
  public static final int grupo = 25;
  public static final int alineado = 27;
  public static final int DIV = 12;
  public static final int justificado = 38;
  public static final int vertical = 34;
  public static final int ID = 39;
  public static final int PUNTO_COMA = 11;
  public static final int visible = 21;
  public static final int EOF = 0;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int capital = 17;
  public static final int COMA = 6;
  public static final int CADENA = 41;
  public static final int MENOS = 8;
  public static final int horizontal = 33;
  public static final int PAR_IZQ = 4;
  public static final int colorText = 24;
  public static final int minuscula = 16;
  public static final int centrado = 37;
  public static final int texto = 28;
  public static final int izquierda = 35;
  public static final int COR_IZQ = 2;
  public static final int formato = 29;
  public static final int borde = 22;
  public static final int FALSE = 19;
  public static final int idToken = 26;
  public static final int cursiva = 14;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COR_IZQ",
  "COR_DER",
  "PAR_IZQ",
  "IGUAL",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "PAR_DER",
  "PUNTO_COMA",
  "DIV",
  "negrilla",
  "cursiva",
  "mayuscula",
  "minuscula",
  "capital",
  "TRUE",
  "FALSE",
  "autoredimension",
  "visible",
  "borde",
  "opaque",
  "colorText",
  "grupo",
  "idToken",
  "alineado",
  "texto",
  "formato",
  "letra",
  "tamTex",
  "fondoElemento",
  "horizontal",
  "vertical",
  "izquierda",
  "derecha",
  "centrado",
  "justificado",
  "ID",
  "NUMERO",
  "CADENA"
  };
}

